version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: team-post-it-server
    ports:
      - "5500:5500"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: team-post-it-client
    ports:
      - "3000:3000"
